del /S /q files\*.*

python get_account_configuration.py "Spain-Augure" "auguretemp123"
python get_account_configuration.py "Admirabilia-Augure" "auguretemp123"
python get_account_configuration.py "Bluworm-Augure" "auguretemp123"
python get_account_configuration.py "Bradek-Augure" "auguretemp123"
python get_account_configuration.py "Evercom-Augure" "auguretemp123"
python get_account_configuration.py "Prisma-Augure" "auguretemp123"
python get_account_configuration.py "Artelier-Augure" "auguretemp123"
python get_account_configuration.py "BursonEmea-Augure" "auguretemp123"
python get_account_configuration.py "Deva-Augure" "auguretemp123"
python get_account_configuration.py "Havas-Augure" "auguretemp123"
python get_account_configuration.py "Lewis-Augure" "auguretemp123"
python get_account_configuration.py "Marco-Augure" "auguretemp123"
python get_account_configuration.py "Onecomunicacion-Augure" "auguretemp123"
python get_account_configuration.py "Anniebonnie-Augure" "auguretemp123"
python get_account_configuration.py "Theoria-Augure" "auguretemp123"
python get_account_configuration.py "Berbes-Augure" "auguretemp123"
python get_account_configuration.py "Comunicacionibero-Augure" "auguretemp123"
python get_account_configuration.py "Gaiacomunicacion-Augure" "auguretemp123"
python get_account_configuration.py "France-Augure" "auguretemp123"
python get_account_configuration.py "Torresycarrera-Augure" "auguretemp123"
python get_account_configuration.py "Keima-Augure" "auguretemp123"
python get_account_configuration.py "Littlewing-Augure" "auguretemp123"
python get_account_configuration.py "Amalthea-Augure" "auguretemp123"
python get_account_configuration.py "Comfi-Augure" "auguretemp123"
python get_account_configuration.py "Spencerlewis-Augure" "auguretemp123"
python get_account_configuration.py "CRC-Augure" "auguretemp123"

merge_configurations.py